language: scala
jdk:
  # see https://github.com/travis-ci/travis-cookbooks/issues/35
  - oraclejdk7
scala:
  - 2.10.0
before_install:
  #- sudo dpkg -r sbt
  #- sudo rm /usr/bin/sbt
  #- wget http://files.travis-ci.org/packages/deb/sbt/sbt-0.12.1.deb -O /tmp/sbt.deb
  #- sudo dpkg -i /tmp/sbt.deb
  - git submodule update --init --recursive
  - cd Play20
  - PLAY_VERSION="2-TLS-`git log -n 1 --pretty=format:%H`"
  - cd ..
  - wget http://bblfish.net/work/repo/builds/Play2/play-${PLAY_VERSION}.tar.bz2
  - tar -xjf play-${PLAY_VERSION}.tar.bz2
script: play-${PLAY_VERSION}/play test  
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  # email: false
   - henry.story@bblfish.net
   - jonathan.dray@gmail.com
